/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#001026',
        'primary-container': '#0b2545',
        'on-primary': '#ffffff',
        'on-primary-container': '#778db2',
        'primary-fixed': '#d5e3ff',
        'primary-fixed-dim': '#b1c7f0',
        'on-primary-fixed': '#001c3b',
        'on-primary-fixed-variant': '#314769',
        'secondary': '#006399',
        'secondary-container': '#67bafd',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#004972',
        'secondary-fixed': '#cde5ff',
        'secondary-fixed-dim': '#94ccff',
        'on-secondary-fixed': '#001d32',
        'on-secondary-fixed-variant': '#004b74',
        'tertiary': '#030049',
        'tertiary-container': '#0b0087',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#7a7dff',
        'tertiary-fixed': '#e1e0ff',
        'tertiary-fixed-dim': '#c0c1ff',
        'on-tertiary-fixed': '#07006c',
        'on-tertiary-fixed-variant': '#2f2ebe',
        'surface': '#faf8ff',
        'surface-dim': '#d2d9f4',
        'surface-bright': '#faf8ff',
        'surface-variant': '#dae2fd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'surface-container-high': '#e2e7ff',
        'surface-container-highest': '#dae2fd',
        'surface-tint': '#495f82',
        'inverse-surface': '#283044',
        'inverse-on-surface': '#eef0ff',
        'inverse-primary': '#b1c7f0',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'on-surface': '#131b2e',
        'on-surface-variant': '#44474e',
        'background': '#faf8ff',
        'on-background': '#131b2e',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.25rem',
        'md': '0.5rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      },
      spacing: {
        'pad-xs': '0.25rem',
        'pad-sm': '0.5rem',
        'pad-md': '1rem',
        'pad-lg': '1.5rem',
        'pad-xl': '2rem',
        'margin-mobile': '1rem',
        'margin-desktop': '2rem',
        'gutter-mobile': '1rem',
        'gutter-desktop': '1.5rem',
        'touch-min': '3rem',
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'spaceGrotesk': ['Space Grotesk', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
        'jetbrainsMono': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'telemetry-lg': ['JetBrains Mono', 'monospace'],
        'telemetry-sm': ['JetBrains Mono', 'monospace'],
        'label-md': ['JetBrains Mono', 'monospace'],
        'label-sm': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg': ['30px', { lineHeight: '38px', fontWeight: '600' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['17px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'telemetry-lg': ['28px', { lineHeight: '32px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'telemetry-sm': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '600' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.06em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
